---
title: "Server Kelompok"
output: html_notebook
---



```{r}
connectDB <- function(){
  driver <- dbDriver('PostgreSQL')
  
  DB <- dbConnect(
    driver,
    dbname="wipfxifr", # User & Default database
    host="topsy.db.elephantsql.com", # Server
    # port=5433,
    user="wipfxifr", # User & Default database
    password="-oPyYlWQc7bxoGv7gH6O5fz0v_vlrhW" # Password
  )
}

function(input, output, session) {
  output$tblmatches <- renderDataTable({
    DB <- connectDB()
    matches<-dbReadTable(DB, 'matches')
    dbDisconnect(DB)
    
    matches
  })
  
  output$tblplayers <- renderDataTable({
    DB <- connectDB()
    players<-dbReadTable(DB, 'players')
    dbDisconnect(DB)
    
    players
  })
  
  output$tblresult <- renderDataTable({
    DB <- connectDB()
    result<-dbReadTable(DB, 'result')
    dbDisconnect(DB)
    
    result
  })
  
  output$tblscores <- renderDataTable({
    DB <- connectDB()
    scores<-dbReadTable(DB, 'scores')
    dbDisconnect(DB)
    
    scores
  })
  
  output$tblstadiums <- renderDataTable({
    DB <- connectDB()
    stadiums<-dbReadTable(DB, 'stadiums')
    dbDisconnect(DB)
    
    stadiums
  })
  
  output$tblteams <- renderDataTable({
    DB <- connectDB()
    teams<-dbReadTable(DB, 'teams')
    dbDisconnect(DB)
    
    teams
  })
  
  listDr <- reactive({
    DB <- connectDB()
    players<-dbReadTable(DB, 'players')
    dbDisconnect(DB)
    
    players$nama_players
  })
  
  output$loadplayers <- renderUI({
    selectInput("listplayer", "Player", choices = listDr())
  })
  
 
}
```


```{r}
library(RPostgreSQL)
driver <- dbDriver('PostgreSQL')
DB <- dbConnect(
  driver, 
  dbname="Sepakbola", 
  host="localhost",
  port=5432,
  user="postgres",
  password="123"
)
```



